import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";

import { assertExpectedOutputs, parseMode, runShowcase } from "../scripts/render.mjs";

const projectDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const designPath = join(projectDirectory, "designs/kiln-ledger.json");
const committedPaths = {
  designPath,
  generatedDirectory: join(projectDirectory, "generated"),
};

test("parses only the supported render mode", () => {
  assert.equal(parseMode([]), "generate");
  assert.equal(parseMode(["--verify"]), "verify");
  assert.throws(() => parseMode(["--force"]), /Unsupported argument/);
});

test("requires exactly one SVG followed by one PNG", () => {
  assert.doesNotThrow(() =>
    assertExpectedOutputs([{ format: "svg" }, { format: "png" }]),
  );
  assert.throws(
    () => assertExpectedOutputs([{ format: "svg" }, { format: "svg" }]),
    /Expected exactly one SVG and one PNG/,
  );
  assert.throws(
    () => assertExpectedOutputs([{ format: "svg" }]),
    /Expected exactly one SVG and one PNG/,
  );
});

test("verifies the reviewed committed graphic", async () => {
  const result = await runShowcase("verify", committedPaths);
  assert.deepEqual(
    result.outputs.map((output) => output.format),
    ["svg", "png"],
  );
  assert.equal(result.qualityIssues.length, 0);
});

test("generates reproducible files and detects stale outputs", async () => {
  const temporaryDirectory = await mkdtemp(join(tmpdir(), "glyphkiln-showcase-"));
  const paths = {
    designPath,
    generatedDirectory: join(temporaryDirectory, "generated"),
  };

  try {
    const generated = await runShowcase("generate", paths);
    await runShowcase("verify", paths);
    const pngPath = join(paths.generatedDirectory, "kiln-ledger.png");
    const manifest = JSON.parse(await readFile(`${pngPath}.manifest.json`, "utf8"));
    assert.equal(manifest.output.sha256, generated.outputs[1].manifest.output.sha256);

    const stalePath = join(paths.generatedDirectory, "stale.txt");
    await writeFile(stalePath, "unexpected", "utf8");
    await assert.rejects(
      runShowcase("verify", paths),
      /Generated output set does not match/,
    );
    await rm(stalePath);

    await writeFile(pngPath, "changed", "utf8");
    await assert.rejects(
      runShowcase("verify", paths),
      /kiln-ledger\.png does not match generated bytes/,
    );
  } finally {
    await rm(temporaryDirectory, { recursive: true, force: true });
  }
});
