import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, relative } from "node:path";

import { Resvg } from "@resvg/resvg-js";
import * as fontkit from "fontkit";

export function createQualificationEmitter({ repositoryRoot, verify }) {
  function repositoryPath(path) {
    return relative(repositoryRoot, path).replaceAll("\\", "/");
  }

  async function emit(path, value) {
    const bytes = typeof value === "string" ? new TextEncoder().encode(value) : value;
    if (verify) {
      const current = new Uint8Array(await readFile(path));
      if (!Buffer.from(current).equals(Buffer.from(bytes))) {
        throw new Error(`${repositoryPath(path)} does not match generated bytes.`);
      }
      return;
    }
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, bytes);
  }

  return { emit, repositoryPath };
}

export function outlineText(bytes, text, options) {
  const created = fontkit.create(Buffer.from(bytes));
  if (!("layout" in created)) throw new Error("Expected a single font face.");
  const face =
    created.variationAxes.wght === undefined
      ? created
      : created.getVariation({ wght: options.weight });
  const run = face.layout(text);
  const scale = options.fontSize / face.unitsPerEm;
  let penX = options.x;
  const paths = [];
  for (const [index, glyph] of run.glyphs.entries()) {
    const position = run.positions[index];
    paths.push(
      serializePath(
        glyph.path.commands,
        scale,
        penX + position.xOffset * scale,
        options.baseline - position.yOffset * scale,
      ),
    );
    penX += position.xAdvance * scale + options.letterSpacing;
  }
  return paths.join(" ");
}

export function renderSvg(svg, width) {
  return new Uint8Array(
    new Resvg(svg, { fitTo: { mode: "width", value: width } }).render().asPng(),
  );
}

function serializePath(commands, scale, offsetX, offsetY) {
  return commands
    .map((command) => {
      const points = command.args.map((value, index) =>
        coordinate(index % 2 === 0 ? offsetX + value * scale : offsetY - value * scale),
      );
      switch (command.command) {
        case "moveTo":
          return `M ${points.join(" ")}`;
        case "lineTo":
          return `L ${points.join(" ")}`;
        case "quadraticCurveTo":
          return `Q ${points.join(" ")}`;
        case "bezierCurveTo":
          return `C ${points.join(" ")}`;
        case "closePath":
          return "Z";
        default:
          throw new Error(`Unsupported path command ${command.command}.`);
      }
    })
    .join(" ");
}

function coordinate(value) {
  const rounded = Math.round(value * 1_000) / 1_000;
  return String(Object.is(rounded, -0) ? 0 : rounded);
}
